name: 'Label and Assign'
description: 'Automatically label and assign new pull requests based on the paths of files being changed'
author: 'Contractify'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the label and assignment configurations'
    default: '.github/label-and-assign.yml'
    required: false

branding:
  icon: user
  color: green

runs:
  using: 'node20'
  main: 'dist/index.js'
